/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.tripp.bowling;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BowlingTest {
	private final Bowling bowling = new Bowling();
	
    @Test
    void gutterGameScoresZero() {
    	repeatRoll(0, 20);
    	assertEquals(0, bowling.score());
    }
    
    @Test
    void allOnesScoresTwenty() {
    	repeatRoll(1, 20);
    	assertEquals(20, bowling.score());
    }

    @Test
    void spareGivesNextRollAsBonus() {
    	bowling.roll(5);
    	bowling.roll(5);
    	bowling.roll(3);
    	repeatRoll(0, 17);
    	
    	assertEquals(16, bowling.score());
    }
    
    @Test
    void allSpares() {
    	repeatRoll(5, 21);
    	assertEquals(150, bowling.score());
    }
    
    @Test
    void aStrikeGivesTwoBonusRolls() {
    	bowling.roll(10);
    	bowling.roll(3);
    	bowling.roll(4);
    	repeatRoll(0, 16);
    	
    	assertEquals(24, bowling.score());
    }
    
    @Test
    void perfectGame() {
    	repeatRoll(10, 12);
    	assertEquals(300, bowling.score());
    }

	private void repeatRoll(int n, int times) {
		for(int i = 0; i < times; i++) { bowling.roll(n); }
	}
}
