/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.tripp.bowling;

import java.util.ArrayList;
import java.util.List;

public class Bowling {
    public static void main(String[] args) {
        System.out.println("Hello");
    }

    private final List<Integer> rolls = new ArrayList<>();

    public void roll(int i) {
        getRolls().add(i);
    }

    public int score() {
        return doScore(getRolls());
    }

    public List<Integer> getRolls() {
        return rolls;
    }

    private int doScore(List<Integer> rolls) {
        int x = rolls.size() > 0 ? rolls.get(0) : 0;
        int y = rolls.size() > 1 ? rolls.get(1) : 0;
        int z = rolls.size() > 2 ? rolls.get(2) : 0;

        if(rolls.size() <= 3) { return x + y + z; }

        if(x == 10) {
            return x + y + z + doScore(rolls.subList(1, rolls.size()));
        }
        if(x + y == 10) {
            return x + y + z + doScore(rolls.subList(2, rolls.size()));
        }
        return x + y + doScore(rolls.subList(2, rolls.size()));
    }
}
